const categories = {
  'AI i dane': { color: '#b86b53', icon: '✦' },
  'Web i strony': { color: '#577d92', icon: '◌' },
  'Kod i narzędzia': { color: '#7c6d9c', icon: '⌘' },
  'Tekst i treść': { color: '#9b8054', icon: 'Aa' },
  'Komputer': { color: '#5f9676', icon: '▣' },
  'Projektowanie': { color: '#ad7181', icon: '◇' },
};

const seedTerms = [
  { id: 'prompt', title: 'Prompt', category: 'AI i dane', definition: 'Instrukcja lub polecenie przekazane modelowi AI. Dobry prompt mówi, co ma powstać, dla kogo, w jakim formacie i z jakimi ograniczeniami.', context: 'Prompt jest jak brief dla współpracownika — im jaśniejszy cel i kontekst, tym mniej zgadywania po drugiej stronie.', example: 'Napisz opis produktu w 3 zdaniach. Ton: spokojny i konkretny. Odbiorca: osoba początkująca.', tags: ['AI', 'instrukcja'], related: ['LLM', 'RAG', 'Fine-tuning'] },
  { id: 'llm', title: 'LLM', category: 'AI i dane', definition: 'Large Language Model — duży model językowy, który rozpoznaje wzorce w języku i generuje tekst na podstawie kontekstu.', context: 'Chatboty, tłumacze i asystenci tekstowi korzystają z LLM. Model nie „myśli” jak człowiek — przewiduje najbardziej prawdopodobną kolejną część wypowiedzi.', example: 'ChatGPT, Claude i Gemini to aplikacje korzystające z modeli językowych.', tags: ['AI', 'model'], related: ['Prompt', 'Token', 'API'] },
  { id: 'rag', title: 'RAG', category: 'AI i dane', definition: 'Retrieval-Augmented Generation — sposób pracy, w którym AI najpierw wyszukuje informacje w wybranych źródłach, a dopiero potem buduje odpowiedź.', context: 'RAG pomaga ograniczyć zmyślanie i pozwala odpowiadać na podstawie Twoich dokumentów, instrukcji albo bazy wiedzy.', example: 'Pytanie → wyszukanie fragmentów w dokumentacji → odpowiedź AI z wykorzystaniem tych fragmentów.', tags: ['AI', 'wyszukiwanie'], related: ['LLM', 'Embedding', 'Baza danych'] },
  { id: 'token', title: 'Token', category: 'AI i dane', definition: 'Mały fragment tekstu, na który model językowy dzieli zdanie. Tokenem może być całe słowo, jego część, znak lub spacja.', context: 'Liczba tokenów wpływa na długość kontekstu i koszt korzystania z API. Token to nie zawsze jedno słowo.', example: 'Zdanie „To jest test.” zostanie podzielone na kilka tokenów — zależnie od modelu i języka.', tags: ['AI', 'tekst'], related: ['LLM', 'Kontekst', 'API'] },
  { id: 'api', title: 'API', category: 'Kod i narzędzia', definition: 'Application Programming Interface — ustalony sposób, w jaki jeden program może poprosić inny program o dane lub wykonanie operacji.', context: 'API jest jak menu w restauracji: opisuje, co można zamówić i w jakiej formie, bez pokazywania, jak działa kuchnia.', example: 'Aplikacja pogodowa pobiera aktualną temperaturę, wysyłając zapytanie do API serwisu pogodowego.', tags: ['kod', 'integracje'], related: ['Endpoint', 'JSON', 'HTTP'] },
  { id: 'html', title: 'HTML', category: 'Web i strony', definition: 'Język znaczników, który opisuje strukturę strony internetowej: nagłówki, akapity, linki, obrazy, formularze i sekcje.', context: 'HTML mówi, czym jest element. CSS określa, jak wygląda, a JavaScript — jak reaguje.', example: '<h1>Moja strona</h1>\n<p>To jest pierwszy akapit.</p>', tags: ['web', 'struktura'], related: ['CSS', 'DOM', 'Semantyka'] },
  { id: 'css', title: 'CSS', category: 'Web i strony', definition: 'Cascading Style Sheets — język stylów opisujący wygląd strony: kolory, odstępy, układ, typografię i zachowanie na różnych ekranach.', context: 'CSS pozwala oddzielić treść od prezentacji. Dzięki media queries strona może wyglądać dobrze na komputerze i telefonie.', example: '.card {\n  padding: 24px;\n  border-radius: 12px;\n  background: #fff;\n}', tags: ['web', 'design'], related: ['HTML', 'Flexbox', 'Responsive'] },
  { id: 'javascript', title: 'JavaScript', category: 'Kod i narzędzia', definition: 'Język programowania używany między innymi do dodawania interakcji i logiki na stronach oraz w aplikacjach webowych.', context: 'JavaScript może reagować na kliknięcia, zmieniać treść strony, pobierać dane i zapisywać ustawienia użytkownika.', example: "button.addEventListener('click', () => {\n  console.log('Działa!');\n});", tags: ['kod', 'web'], related: ['DOM', 'Frontend', 'TypeScript'] },
  { id: 'frontend', title: 'Frontend', category: 'Web i strony', definition: 'Część aplikacji, którą widzi i obsługuje użytkownik: ekrany, przyciski, formularze, animacje i reakcje na działanie.', context: 'Frontend działa zwykle w przeglądarce. Dobra warstwa frontendowa łączy czytelny interfejs z logiką aplikacji.', example: 'Widok wyszukiwarki, karta hasła i przycisk „Dodaj” należą do frontendu.', tags: ['web', 'interfejs'], related: ['Backend', 'UI', 'JavaScript'] },
  { id: 'backend', title: 'Backend', category: 'Kod i narzędzia', definition: 'Część aplikacji działająca po stronie serwera: przechowuje dane, wykonuje operacje i udostępnia je frontendowi.', context: 'Użytkownik zwykle nie widzi backendu bezpośrednio, ale to on obsługuje konta, bazy danych i reguły aplikacji.', example: 'Po zapisaniu nowego hasła backend może zweryfikować dane i umieścić je w bazie.', tags: ['kod', 'serwer'], related: ['Frontend', 'Baza danych', 'Endpoint'] },
  { id: 'dom', title: 'DOM', category: 'Web i strony', definition: 'Document Object Model — drzewiasty model dokumentu HTML, który JavaScript może odczytywać i zmieniać.', context: 'Kiedy skrypt podmienia tekst nagłówka albo dodaje nową kartę, pracuje na DOM-ie strony.', example: "document.querySelector('h1').textContent = 'Nowy tytuł';", tags: ['web', 'JavaScript'], related: ['HTML', 'JavaScript', 'Event'] },
  { id: 'json', title: 'JSON', category: 'Kod i narzędzia', definition: 'Lekki format zapisu danych oparty na parach klucz–wartość. Jest czytelny dla ludzi i łatwy do przetwarzania przez programy.', context: 'JSON jest częstym językiem wymiany danych między frontendem, backendem i API.', example: '{\n  "title": "CSS",\n  "category": "Web i strony"\n}', tags: ['dane', 'format'], related: ['API', 'JavaScript', 'Baza danych'] },
  { id: 'git', title: 'Git', category: 'Kod i narzędzia', definition: 'System kontroli wersji, który zapisuje historię zmian w plikach i pozwala bezpiecznie pracować nad kodem.', context: 'Git pozwala wrócić do wcześniejszej wersji, porównać zmiany i współpracować bez nadpisywania pracy innych osób.', example: 'git add .\ngit commit -m "Dodaj wyszukiwarkę"', tags: ['narzędzia', 'wersje'], related: ['Repository', 'Branch', 'Deploy'] },
  { id: 'repository', title: 'Repository', category: 'Kod i narzędzia', definition: 'Repozytorium — katalog projektu śledzony przez Git, zawierający pliki oraz historię ich zmian.', context: 'Repozytorium może być lokalne na komputerze albo przechowywane zdalnie, np. na GitHubie.', example: 'Repozytorium aplikacji zawiera kod, pliki stylów, instrukcję i konfigurację.', tags: ['Git', 'projekt'], related: ['Git', 'Branch', 'GitHub'] },
  { id: 'responsive', title: 'Responsive', category: 'Web i strony', definition: 'Projektowanie strony tak, aby układ i elementy dopasowywały się do szerokości ekranu — od telefonu po duży monitor.', context: 'Responsywność to nie tylko zmniejszanie elementów. To także priorytetyzowanie treści, wygodne dotykanie i czytelna nawigacja.', example: '@media (max-width: 720px) {\n  .layout { grid-template-columns: 1fr; }\n}', tags: ['web', 'mobile'], related: ['CSS', 'Mobile first', 'UI'] },
  { id: 'ui', title: 'UI', category: 'Projektowanie', definition: 'User Interface — interfejs użytkownika, czyli wizualna i interaktywna warstwa produktu: układ, kolory, typografia i kontrolki.', context: 'Dobre UI pomaga zrozumieć, co można zrobić i co wydarzy się po kliknięciu.', example: 'Przycisk, pole wyszukiwania i karta wyniku to elementy UI.', tags: ['design', 'interfejs'], related: ['UX', 'Komponent', 'Accessibility'] },
  { id: 'ux', title: 'UX', category: 'Projektowanie', definition: 'User Experience — doświadczenie użytkownika podczas korzystania z produktu: łatwość, logika, tempo i poczucie kontroli.', context: 'UX zaczyna się przed wyglądem. Pytanie brzmi: czy użytkownik bez zastanawiania osiągnie swój cel?', example: 'Wyszukiwarka, która działa od razu po wpisaniu słowa, poprawia UX leksykonu.', tags: ['design', 'użyteczność'], related: ['UI', 'Flow', 'Accessibility'] },
  { id: 'accessibility', title: 'Accessibility', category: 'Projektowanie', definition: 'Dostępność — projektowanie produktu tak, aby mogły z niego korzystać osoby o różnych potrzebach i sposobach obsługi.', context: 'To między innymi odpowiedni kontrast, klawiatura, opisy dla czytników ekranu i czytelne komunikaty.', example: 'Przycisk z etykietą „Wyczyść wyszukiwanie” jest lepszy niż sam ozdobny znak bez opisu.', tags: ['design', 'web'], related: ['UI', 'UX', 'Semantyka'] },
  { id: 'ssd', title: 'SSD', category: 'Komputer', definition: 'Solid State Drive — szybki dysk oparty na pamięci flash, bez ruchomych części mechanicznych.', context: 'SSD przyspiesza uruchamianie systemu, aplikacji i plików. Jest zwykle szybszy i cichszy niż starszy dysk HDD.', example: 'Przeniesienie programu do uruchamiania z SSD często wyraźnie skraca czas startu.', tags: ['sprzęt', 'dysk'], related: ['RAM', 'CPU', 'Backup'] },
  { id: 'ram', title: 'RAM', category: 'Komputer', definition: 'Pamięć operacyjna komputera, w której tymczasowo przechowywane są dane używane przez uruchomione programy.', context: 'Więcej RAM-u pomaga pracować z większą liczbą aplikacji jednocześnie. Po wyłączeniu komputera zawartość RAM-u znika.', example: 'Przeglądarka z wieloma kartami i edytor grafiki mogą potrzebować dużo RAM-u.', tags: ['sprzęt', 'pamięć'], related: ['SSD', 'CPU', 'Cache'] },
  { id: 'cache', title: 'Cache', category: 'Komputer', definition: 'Pamięć podręczna — szybkie miejsce na dane, które mogą przydać się ponownie, aby nie pobierać lub nie obliczać ich od początku.', context: 'Cache przyspiesza aplikacje, ale czasem stara kopia danych powoduje, że nie widzisz najnowszej wersji strony.', example: 'Wyczyszczenie cache przeglądarki może pomóc, gdy strona wyświetla nieaktualne pliki.', tags: ['wydajność', 'dane'], related: ['RAM', 'CDN', 'Cookies'] },
  { id: 'markdown', title: 'Markdown', category: 'Tekst i treść', definition: 'Prosty sposób formatowania tekstu za pomocą znaków, np. # dla nagłówka, ** dla pogrubienia i - dla listy.', context: 'Markdown jest popularny w dokumentacji, notatkach, README i narzędziach dla programistów.', example: '# Tytuł\n\nTo jest **ważna** informacja.\n\n- pierwszy punkt', tags: ['tekst', 'dokumentacja'], related: ['HTML', 'README', 'CMS'] },
  { id: 'seo', title: 'SEO', category: 'Web i strony', definition: 'Search Engine Optimization — działania, które pomagają stronie być lepiej rozumianą i znajdowaną w wyszukiwarkach.', context: 'SEO obejmuje treść, strukturę HTML, szybkość, linki i dopasowanie strony do intencji osoby szukającej.', example: 'Opisowa nazwa strony, sensowny nagłówek i użyteczna odpowiedź są lepsze niż upychanie słów kluczowych.', tags: ['web', 'treść'], related: ['HTML', 'Meta tag', 'Keyword'] },
  { id: 'deploy', title: 'Deploy', category: 'Web i strony', definition: 'Publikacja aplikacji lub strony w środowisku, z którego mogą korzystać inni użytkownicy.', context: 'Deploy może oznaczać wysłanie nowej wersji do hostingu, uruchomienie jej i sprawdzenie, czy działa poprawnie.', example: 'Po deployu leksykon jest dostępny pod publicznym adresem zamiast tylko na Twoim komputerze.', tags: ['web', 'publikacja'], related: ['Hosting', 'Build', 'Git'] },
  { id: 'build', title: 'Build', category: 'Kod i narzędzia', definition: 'Proces przygotowania kodu do uruchomienia lub publikacji: kompilacja, optymalizacja i spakowanie plików.', context: 'Wynikiem buildu są zwykle pliki produkcyjne, które można wdrożyć na serwerze.', example: 'npm run build', tags: ['narzędzia', 'publikacja'], related: ['Deploy', 'Frontend', 'npm'] },
  { id: 'cms', title: 'CMS', category: 'Web i strony', definition: 'Content Management System — system do tworzenia, edytowania i publikowania treści bez ręcznej zmiany kodu.', context: 'CMS oddziela treść od technicznej budowy strony, dzięki czemu artykuły może dodawać także osoba nietechniczna.', example: 'WordPress, Ghost i Sanity to przykłady systemów CMS.', tags: ['web', 'treść'], related: ['SEO', 'Markdown', 'Backend'] },
];

const extraTerms = [
  { id: 'embedding', title: 'Embedding', category: 'AI i dane', definition: 'Reprezentacja tekstu, obrazu lub innego obiektu w postaci wektora liczb, który zachowuje znaczenie i podobieństwa.', context: 'Embedding pozwala wyszukiwać treści po sensie, a nie tylko po identycznych słowach.', example: 'Pytanie o szybką pamięć komputera może znaleźć fragment o RAM-ie, nawet jeśli nie zawiera słowa RAM.', tags: ['AI', 'wektory'], related: ['RAG', 'Baza wektorowa', 'Token'] },
  { id: 'fine-tuning', title: 'Fine-tuning', category: 'AI i dane', definition: 'Dodatkowe trenowanie gotowego modelu na specjalnie przygotowanych danych, aby lepiej wykonywał określone zadanie.', context: 'Fine-tuning zmienia zachowanie modelu, ale nie jest tym samym co dodawanie aktualnych dokumentów do kontekstu.', example: 'Model może zostać dostrojony do klasyfikowania zgłoszeń według kategorii obsługi klienta.', tags: ['AI', 'model'], related: ['LLM', 'Dataset', 'Inference'] },
  { id: 'hallucination', title: 'Hallucination', category: 'AI i dane', definition: 'Zmyślona lub niepoprawna odpowiedź modelu AI przedstawiona w sposób brzmiący wiarygodnie.', context: 'Model może tworzyć nieistniejące źródła, liczby albo fakty. Ważne informacje trzeba sprawdzać w źródłach.', example: 'AI podaje artykuł naukowy z realistycznym tytułem, ale po sprawdzeniu okazuje się, że taki artykuł nie istnieje.', tags: ['AI', 'ryzyko'], related: ['RAG', 'Ewaluacja', 'Guardrails'] },
  { id: 'context-window', title: 'Context window', category: 'AI i dane', definition: 'Maksymalna ilość tekstu i innych danych, które model może uwzględnić w jednej rozmowie lub zapytaniu.', context: 'Kontekst obejmuje między innymi instrukcję systemową, historię rozmowy, dokumenty i bieżące pytanie.', example: 'Jeśli dokument przekracza okno kontekstowe, trzeba go podzielić albo wcześniej streścić.', tags: ['AI', 'tekst'], related: ['Token', 'LLM', 'RAG'] },
  { id: 'temperature', title: 'Temperature', category: 'AI i dane', definition: 'Parametr generowania, który wpływa na losowość wyboru kolejnych słów przez model.', context: 'Niższa temperatura zwykle daje bardziej przewidywalne odpowiedzi, a wyższa sprzyja różnorodności.', example: 'Do ekstrakcji danych ustaw niską temperaturę, a do burzy pomysłów wybierz wyższą.', tags: ['AI', 'parametr'], related: ['LLM', 'Prompt', 'Ewaluacja'] },
  { id: 'vector-database', title: 'Baza wektorowa', category: 'AI i dane', definition: 'Baza danych przeznaczona do przechowywania wektorów i szybkiego wyszukiwania obiektów o podobnym znaczeniu.', context: 'Bazy wektorowe są często używane w systemach RAG i wyszukiwaniu semantycznym.', example: 'Po zamianie akapitów dokumentacji na embeddingi baza wektorowa znajduje te najbardziej podobne do pytania.', tags: ['AI', 'dane'], related: ['Embedding', 'RAG', 'SQL'] },
  { id: 'inference', title: 'Inference', category: 'AI i dane', definition: 'Proces użycia wytrenowanego modelu do wygenerowania przewidywania, klasyfikacji albo odpowiedzi.', context: 'Trening uczy model, a inference wykorzystuje jego gotową wiedzę przy konkretnym zapytaniu.', example: 'Wysłanie promptu do API i otrzymanie odpowiedzi jest etapem inference.', tags: ['AI', 'model'], related: ['Fine-tuning', 'LLM', 'API'] },
  { id: 'dataset', title: 'Dataset', category: 'AI i dane', definition: 'Zestaw danych używany do trenowania, testowania lub oceniania modelu albo systemu.', context: 'Jakość, różnorodność i sposób opisania danych mocno wpływają na wynik modelu.', example: 'Dataset do rozpoznawania zdjęć zawiera obrazy oraz etykiety mówiące, co przedstawiają.', tags: ['AI', 'dane'], related: ['Machine learning', 'Fine-tuning', 'Ewaluacja'] },
  { id: 'machine-learning', title: 'Machine learning', category: 'AI i dane', definition: 'Uczenie maszynowe — metody, w których program uczy się wzorców z danych zamiast otrzymywać każdą regułę ręcznie.', context: 'Model uczy się na przykładach, a potem stosuje rozpoznane zależności do nowych danych.', example: 'Filtr antyspamowy uczy się odróżniać wiadomości niechciane na podstawie wcześniejszych przykładów.', tags: ['AI', 'dane'], related: ['Dataset', 'Neural network', 'Inference'] },
  { id: 'neural-network', title: 'Neural network', category: 'AI i dane', definition: 'Sieć neuronowa — model złożony z połączonych warstw obliczeniowych, który potrafi uczyć się złożonych wzorców.', context: 'Sieci neuronowe są podstawą wielu współczesnych modeli językowych, obrazowych i dźwiękowych.', example: 'Sieć neuronowa może nauczyć się rozpoznawać, czy na zdjęciu znajduje się kot.', tags: ['AI', 'model'], related: ['Machine learning', 'Deep learning', 'GPU'] },
  { id: 'computer-vision', title: 'Computer vision', category: 'AI i dane', definition: 'Widzenie komputerowe — obszar AI zajmujący się rozpoznawaniem i analizą obrazów oraz nagrań.', context: 'System może wykrywać obiekty, odczytywać tekst, porównywać obrazy albo opisywać scenę.', example: 'Aplikacja odczytuje tekst z fotografii rachunku i zamienia go na dane.', tags: ['AI', 'obrazy'], related: ['Multimodal', 'Embedding', 'Dataset'] },
  { id: 'nlp', title: 'NLP', category: 'AI i dane', definition: 'Natural Language Processing — przetwarzanie języka naturalnego przez komputery.', context: 'NLP obejmuje między innymi tłumaczenie, rozpoznawanie intencji, analizę sentymentu i generowanie tekstu.', example: 'Sklep analizuje opinie klientów i oznacza je jako pozytywne, neutralne albo negatywne.', tags: ['AI', 'język'], related: ['LLM', 'Token', 'Embedding'] },
  { id: 'ai-agent', title: 'AI agent', category: 'AI i dane', definition: 'System AI, który może planować kolejne kroki, korzystać z narzędzi i wykonywać zadanie w kilku etapach.', context: 'Agent różni się od zwykłego generatora tekstu tym, że działa w pętli: obserwuje, decyduje, wykonuje i sprawdza.', example: 'Agent wyszukuje dokumentację, wybiera właściwe API, tworzy szkic kodu i uruchamia test.', tags: ['AI', 'automatyzacja'], related: ['Tool calling', 'Prompt', 'API'] },
  { id: 'system-prompt', title: 'System prompt', category: 'AI i dane', definition: 'Najważniejsza instrukcja przekazywana modelowi, która określa jego rolę, zasady i sposób odpowiadania.', context: 'System prompt powinien zawierać trwałe reguły, a zadanie użytkownika — konkretną prośbę do wykonania.', example: 'Jesteś redaktorem technicznym. Pisz po polsku i wyjaśniaj skróty przy pierwszym użyciu.', tags: ['AI', 'instrukcja'], related: ['Prompt', 'Guardrails', 'LLM'] },
  { id: 'multimodal', title: 'Multimodal', category: 'AI i dane', definition: 'Zdolność modelu do pracy z więcej niż jednym typem danych, np. tekstem, obrazem, dźwiękiem lub wideo.', context: 'Model multimodalny może połączyć opis tekstowy z tym, co widzi na zdjęciu albo słyszy w nagraniu.', example: 'Wysyłasz zdjęcie błędu na ekranie i pytasz AI, co może oznaczać.', tags: ['AI', 'obrazy'], related: ['LLM', 'Computer vision', 'Embedding'] },
  { id: 'evaluation', title: 'Ewaluacja', category: 'AI i dane', definition: 'Systematyczne sprawdzanie jakości, poprawności i bezpieczeństwa modelu albo aplikacji AI.', context: 'Ewaluacja powinna korzystać z przygotowanych przykładów testowych, a nie tylko z pojedynczego udanego wyniku.', example: 'Porównujesz 50 odpowiedzi AI z kluczem i mierzysz, ile z nich spełnia wymagany format.', tags: ['AI', 'jakość'], related: ['Dataset', 'Hallucination', 'Guardrails'] },
  { id: 'guardrails', title: 'Guardrails', category: 'AI i dane', definition: 'Zasady, filtry i kontrole ograniczające niepożądane zachowanie systemu AI.', context: 'Guardrails mogą sprawdzać format, źródła, zakres tematów, dane osobowe i uprawnienia do narzędzi.', example: 'Aplikacja blokuje odpowiedź, jeśli model nie potrafi podać źródła informacji.', tags: ['AI', 'bezpieczeństwo'], related: ['System prompt', 'Ewaluacja', 'Auth'] },
  { id: 'synthetic-data', title: 'Synthetic data', category: 'AI i dane', definition: 'Dane syntetyczne — sztucznie wygenerowane przykłady używane do testowania, treningu lub uzupełniania danych.', context: 'Dane syntetyczne mogą chronić prywatność, ale powinny być sprawdzane pod kątem podobieństwa do prawdziwego problemu.', example: 'Zamiast prawdziwych danych klientów tworzysz fikcyjne rekordy do testu formularza.', tags: ['AI', 'dane'], related: ['Dataset', 'Privacy', 'Ewaluacja'] },
  { id: 'zero-shot', title: 'Zero-shot', category: 'AI i dane', definition: 'Wykonanie zadania przez model bez podawania mu przykładowych odpowiedzi w promptcie.', context: 'Model dostaje tylko opis zadania i korzysta z ogólnych wzorców, których nauczył się wcześniej.', example: 'Klasyfikujesz opinię jako pozytywną lub negatywną, nie pokazując wcześniej żadnej oznaczonej opinii.', tags: ['AI', 'prompt'], related: ['Few-shot', 'Prompt', 'LLM'] },
  { id: 'few-shot', title: 'Few-shot', category: 'AI i dane', definition: 'Technika podawania modelowi kilku przykładów pokazujących oczekiwany sposób rozwiązania zadania.', context: 'Przykłady pomagają modelowi zrozumieć format i poziom szczegółowości bez dodatkowego trenowania.', example: 'Pokazujesz trzy hasła zapisane według wzoru, a następnie prosisz o opracowanie czwartego.', tags: ['AI', 'prompt'], related: ['Zero-shot', 'Prompt', 'Fine-tuning'] },
  { id: 'http', title: 'HTTP', category: 'Web i strony', definition: 'Hypertext Transfer Protocol — protokół, według którego przeglądarka i serwer wymieniają żądania oraz odpowiedzi.', context: 'HTTP opisuje między innymi adres, metodę, nagłówki, status i treść przesyłanej wiadomości.', example: 'Przeglądarka wysyła GET /index.html, a serwer odpowiada plikiem strony.', tags: ['web', 'protokół'], related: ['HTTPS', 'API', 'Status code'] },
  { id: 'https', title: 'HTTPS', category: 'Web i strony', definition: 'Bezpieczna wersja HTTP, w której połączenie jest szyfrowane za pomocą TLS.', context: 'HTTPS chroni dane przesyłane między przeglądarką a serwerem i pomaga potwierdzić tożsamość strony.', example: 'Adres zaczynający się od https:// szyfruje hasło wpisywane do formularza logowania.', tags: ['web', 'bezpieczeństwo'], related: ['HTTP', 'SSL/TLS', 'Certificate'] },
  { id: 'url', title: 'URL', category: 'Web i strony', definition: 'Uniform Resource Locator — adres wskazujący konkretny zasób w internecie, np. stronę, obraz lub endpoint API.', context: 'URL może zawierać protokół, domenę, ścieżkę, parametry i fragment dokumentu.', example: 'https://ayonis.pl/leksykon?haslo=css', tags: ['web', 'adres'], related: ['Domain', 'DNS', 'HTTP'] },
  { id: 'dns', title: 'DNS', category: 'Web i strony', definition: 'Domain Name System — system tłumaczący łatwe do zapamiętania domeny na adresy IP serwerów.', context: 'Dzięki DNS wpisujesz nazwę strony zamiast ciągu cyfr oznaczającego serwer.', example: 'DNS kieruje ayonis.pl do właściwego serwera, na którym działa aplikacja.', tags: ['web', 'sieć'], related: ['Domain', 'IP address', 'Hosting'] },
  { id: 'domain', title: 'Domain', category: 'Web i strony', definition: 'Domena — czytelna nazwa adresu internetowego, którą można zarejestrować i połączyć z serwerem.', context: 'Domena jest nazwą, a hosting jest miejscem, w którym znajdują się pliki strony.', example: 'ayonis.pl to domena, a /leksykon to ścieżka konkretnej strony.', tags: ['web', 'adres'], related: ['DNS', 'URL', 'Hosting'] },
  { id: 'hosting', title: 'Hosting', category: 'Web i strony', definition: 'Usługa udostępniająca miejsce i zasoby serwera, na którym można uruchomić stronę lub aplikację.', context: 'Hosting może obsługiwać pliki statyczne, backend, bazę danych, domenę i certyfikat HTTPS.', example: 'Po wdrożeniu plików na hostingu użytkownicy otwierają stronę z dowolnego urządzenia.', tags: ['web', 'serwer'], related: ['Deploy', 'Domain', 'CDN'] },
  { id: 'cdn', title: 'CDN', category: 'Web i strony', definition: 'Content Delivery Network — sieć serwerów, która dostarcza pliki użytkownikom z lokalizacji możliwie bliskiej ich urządzeniu.', context: 'CDN przyspiesza obrazy, style i skrypty oraz odciąża główny serwer.', example: 'Użytkownik z Warszawy pobiera logo z europejskiego węzła CDN zamiast z serwera w USA.', tags: ['web', 'wydajność'], related: ['Cache', 'Hosting', 'HTTP'] },
  { id: 'cookie', title: 'Cookie', category: 'Web i strony', definition: 'Mały zapis przechowywany przez przeglądarkę, który pozwala stronie pamiętać wybrane informacje.', context: 'Cookies mogą obsługiwać sesję logowania, preferencje albo analitykę. Nie są tym samym co pamięć lokalna.', example: 'Strona zapisuje wybór trybu ciemnego, aby po ponownym wejściu zachować ustawienie.', tags: ['web', 'prywatność'], related: ['Session', 'Local storage', 'Privacy'] },
  { id: 'session', title: 'Session', category: 'Web i strony', definition: 'Sesja — okres, w którym serwer rozpoznaje kolejne żądania jako pochodzące od tego samego użytkownika lub procesu.', context: 'Sesja umożliwia między innymi pozostanie zalogowanym podczas przechodzenia między stronami.', example: 'Po zalogowaniu serwer nadaje przeglądarce identyfikator sesji.', tags: ['web', 'konto'], related: ['Cookie', 'Auth', 'Backend'] },
  { id: 'ssl-tls', title: 'SSL / TLS', category: 'Web i strony', definition: 'Protokoły szyfrowania połączenia używane do ochrony komunikacji internetowej; współcześnie stosuje się głównie TLS.', context: 'Certyfikat strony potwierdza, że połączenie HTTPS korzysta z prawidłowego szyfrowania.', example: 'Kłódka przy adresie strony oznacza, że przeglądarka nawiązała połączenie TLS.', tags: ['web', 'bezpieczeństwo'], related: ['HTTPS', 'Certificate', 'Encryption'] },
  { id: 'cors', title: 'CORS', category: 'Web i strony', definition: 'Cross-Origin Resource Sharing — zasady określające, czy przeglądarka może pobierać dane z innej domeny.', context: 'CORS chroni użytkownika przed niekontrolowanym dostępem skryptów do zasobów innych stron.', example: 'Frontend na localhost:3000 musi dostać zgodę backendu na api.example.com.', tags: ['web', 'API'], related: ['HTTP', 'Backend', 'Security'] },
  { id: 'webhook', title: 'Webhook', category: 'Web i strony', definition: 'Automatyczne powiadomienie wysyłane przez jeden system do drugiego po wystąpieniu określonego zdarzenia.', context: 'Webhook działa odwrotnie niż zwykłe odpytywanie — to źródło samo informuje odbiorcę, że coś się wydarzyło.', example: 'System płatności wysyła webhook do sklepu po udanym przelewie.', tags: ['web', 'integracje'], related: ['API', 'HTTP', 'Endpoint'] },
  { id: 'semantic-html', title: 'Semantyczny HTML', category: 'Web i strony', definition: 'Używanie znaczników HTML zgodnie z ich znaczeniem, np. header, nav, main, article i button.', context: 'Semantyka pomaga przeglądarkom, czytnikom ekranu, wyszukiwarkom i osobom utrzymującym kod.', example: 'Do akcji użyj <button>, a nie pustego <div> z obsługą kliknięcia.', tags: ['web', 'dostępność'], related: ['HTML', 'Accessibility', 'SEO'] },
  { id: 'flexbox', title: 'Flexbox', category: 'Web i strony', definition: 'Mechanizm CSS do układania elementów w jednym wymiarze — w wierszu albo kolumnie.', context: 'Flexbox świetnie sprawdza się przy wyrównywaniu elementów, odstępach i prostych układach responsywnych.', example: '.toolbar { display: flex; align-items: center; gap: 12px; }', tags: ['CSS', 'układ'], related: ['CSS', 'Grid', 'Responsive'] },
  { id: 'css-grid', title: 'CSS Grid', category: 'Web i strony', definition: 'Mechanizm CSS do budowania układów w wierszach i kolumnach, szczególnie przy większych strukturach strony.', context: 'Grid pozwala jawnie określać kolumny, obszary i odstępy bez ręcznego pozycjonowania elementów.', example: '.cards { display: grid; grid-template-columns: repeat(3, 1fr); }', tags: ['CSS', 'układ'], related: ['CSS', 'Flexbox', 'Responsive'] },
  { id: 'breakpoint', title: 'Breakpoint', category: 'Web i strony', definition: 'Punkt graniczny szerokości ekranu, przy którym układ interfejsu zmienia sposób działania lub wygląd.', context: 'Breakpoint powinien wynikać z momentu, w którym treść przestaje być wygodna, a nie wyłącznie z konkretnych modeli telefonów.', example: 'Przy 720 px boczne menu zamienia się w przycisk otwierający panel.', tags: ['web', 'mobile'], related: ['Responsive', 'CSS', 'Mobile first'] },
  { id: 'pwa', title: 'PWA', category: 'Web i strony', definition: 'Progressive Web App — strona, która może zachowywać się podobnie do aplikacji instalowanej na urządzeniu.', context: 'PWA może mieć ikonę, działać częściowo offline i otwierać się bez typowej ramki przeglądarki.', example: 'Ayonis Leksykon można dodać do ekranu głównego jako skrót aplikacji.', tags: ['web', 'mobile'], related: ['Responsive', 'Service worker', 'Cache'] },
  { id: 'ssr', title: 'SSR', category: 'Web i strony', definition: 'Server-Side Rendering — generowanie HTML-u na serwerze przed wysłaniem go do przeglądarki.', context: 'SSR może przyspieszyć pierwszy widok i pomaga wyszukiwarkom zobaczyć treść bez wykonywania całej logiki w przeglądarce.', example: 'Serwer wysyła gotową stronę artykułu, zanim JavaScript przejmie interakcje.', tags: ['web', 'wydajność'], related: ['CSR', 'SSG', 'Backend'] },
  { id: 'csr', title: 'CSR', category: 'Web i strony', definition: 'Client-Side Rendering — budowanie widoku głównie w przeglądarce po pobraniu JavaScriptu.', context: 'CSR dobrze pasuje do aplikacji interaktywnych, gdzie użytkownik długo pracuje na jednym ekranie.', example: 'Po załadowaniu aplikacja pobiera dane i sama renderuje wyniki wyszukiwania.', tags: ['web', 'frontend'], related: ['SSR', 'JavaScript', 'React'] },
  { id: 'ssg', title: 'SSG', category: 'Web i strony', definition: 'Static Site Generation — przygotowanie gotowych plików HTML przed publikacją strony.', context: 'SSG jest szybkie i proste w hostingu, gdy treść nie musi być generowana przy każdym żądaniu.', example: 'Dokumentacja może zostać zbudowana raz do plików HTML i serwowana z CDN.', tags: ['web', 'publikacja'], related: ['SSR', 'Build', 'CDN'] },
  { id: 'devtools', title: 'DevTools', category: 'Web i strony', definition: 'Narzędzia deweloperskie w przeglądarce służące do inspekcji HTML, CSS, JavaScriptu, sieci i wydajności.', context: 'DevTools pozwalają sprawdzić, dlaczego element nie wygląda poprawnie albo które żądanie się nie udało.', example: 'W zakładce Network sprawdzasz, czy API zwróciło status 200 czy 404.', tags: ['web', 'debugowanie'], related: ['DOM', 'Debugowanie', 'HTTP'] },
  { id: 'sitemap', title: 'Sitemap', category: 'Web i strony', definition: 'Mapa strony — plik opisujący adresy, które powinny zostać znalezione i zindeksowane przez wyszukiwarkę.', context: 'Sitemap pomaga wyszukiwarkom poznać strukturę większej strony, ale nie zastępuje dobrej nawigacji.', example: 'sitemap.xml zawiera listę adresów wszystkich artykułów leksykonu.', tags: ['SEO', 'web'], related: ['SEO', 'robots.txt', 'URL'] },
  { id: 'robots-txt', title: 'robots.txt', category: 'Web i strony', definition: 'Plik z instrukcjami dla robotów wyszukiwarek dotyczącymi odwiedzania wybranych części strony.', context: 'robots.txt nie jest mechanizmem ochrony danych — zablokowane adresy nadal mogą być znane innym osobom.', example: 'Disallow: /panel/ prosi roboty, aby nie odwiedzały ścieżki panelu.', tags: ['SEO', 'web'], related: ['Sitemap', 'SEO', 'Accessibility'] },
  { id: 'browser', title: 'Przeglądarka', category: 'Web i strony', definition: 'Program, który pobiera zasoby z internetu i interpretuje HTML, CSS oraz JavaScript jako interfejs strony.', context: 'Przeglądarka łączy rolę klienta, środowiska uruchomieniowego i narzędzia do ochrony użytkownika.', example: 'Chrome, Firefox, Edge i Safari renderują Ayonis Leksykon jako aplikację webową.', tags: ['web', 'komputer'], related: ['HTML', 'CSS', 'DevTools'] },
  { id: 'typescript', title: 'TypeScript', category: 'Kod i narzędzia', definition: 'Rozszerzenie JavaScriptu dodające typy, które pomagają wykrywać część błędów jeszcze przed uruchomieniem programu.', context: 'TypeScript jest szczególnie użyteczny w większych projektach, gdzie wiele plików i osób korzysta z tych samych danych.', example: 'type Term = { title: string; category: string; };', tags: ['kod', 'JavaScript'], related: ['JavaScript', 'React', 'Compiler'] },
  { id: 'python', title: 'Python', category: 'Kod i narzędzia', definition: 'Czytelny język programowania często używany w automatyzacji, analizie danych, AI i backendzie.', context: 'Python ma rozbudowany ekosystem bibliotek, dzięki czemu można szybko przejść od pomysłu do działającego prototypu.', example: 'print("Witaj, Ayonis!")', tags: ['kod', 'AI'], related: ['Machine learning', 'Backend', 'Interpreter'] },
  { id: 'react', title: 'React', category: 'Kod i narzędzia', definition: 'Biblioteka JavaScript do budowania interfejsów z niezależnych, wielokrotnie używanych komponentów.', context: 'React opisuje, jak interfejs ma wyglądać dla danego stanu danych, zamiast ręcznie zmieniać każdy element DOM-u.', example: 'function Welcome() { return <h1>Witaj!</h1>; }', tags: ['frontend', 'JavaScript'], related: ['Component', 'Frontend', 'TypeScript'] },
  { id: 'component', title: 'Component', category: 'Kod i narzędzia', definition: 'Komponent — samodzielny fragment interfejsu lub kodu, który można używać w wielu miejscach.', context: 'Komponent może przyjmować dane wejściowe i mieć własną logikę, ale powinien mieć jasno określoną odpowiedzialność.', example: 'Jedna karta hasła może być komponentem używanym dla każdego wpisu w leksykonie.', tags: ['kod', 'interfejs'], related: ['React', 'Design system', 'UI'] },
  { id: 'framework', title: 'Framework', category: 'Kod i narzędzia', definition: 'Rozbudowany szkielet aplikacji, który narzuca lub podpowiada sposób organizacji projektu i udostępnia gotowe mechanizmy.', context: 'Framework daje strukturę i konwencje, dzięki czemu nie trzeba samodzielnie budować podstawowych elementów aplikacji.', example: 'Next.js dostarcza routing, renderowanie i narzędzia do budowania aplikacji webowych.', tags: ['kod', 'narzędzia'], related: ['Library', 'React', 'Runtime'] },
  { id: 'library', title: 'Library', category: 'Kod i narzędzia', definition: 'Biblioteka — gotowy zbiór kodu, który programista dołącza do własnej aplikacji, aby skorzystać z konkretnych funkcji.', context: 'W odróżnieniu od frameworka to aplikacja zwykle decyduje, kiedy wywołać bibliotekę.', example: 'Biblioteka do formatowania dat oszczędza pisania i testowania własnych funkcji daty.', tags: ['kod', 'narzędzia'], related: ['Framework', 'Dependency', 'npm'] },
  { id: 'npm', title: 'npm', category: 'Kod i narzędzia', definition: 'Popularny menedżer pakietów dla ekosystemu JavaScript i nazwa publicznego rejestru paczek.', context: 'npm pozwala instalować biblioteki, uruchamiać skrypty i zapisywać zależności projektu.', example: 'npm install date-fns', tags: ['JavaScript', 'narzędzia'], related: ['Package manager', 'Dependency', 'Build'] },
  { id: 'package-manager', title: 'Package manager', category: 'Kod i narzędzia', definition: 'Menedżer pakietów — narzędzie do instalowania, aktualizowania i blokowania wersji zależności projektu.', context: 'Menedżer pilnuje, aby projekt i inne osoby pracujące nad nim korzystały z tych samych paczek.', example: 'package-lock.json zapisuje dokładne wersje pobranych zależności npm.', tags: ['kod', 'narzędzia'], related: ['npm', 'Dependency', 'Build'] },
  { id: 'cli', title: 'CLI', category: 'Kod i narzędzia', definition: 'Command Line Interface — interfejs tekstowy, w którym program obsługuje się za pomocą poleceń.', context: 'CLI dobrze nadaje się do powtarzalnych operacji, automatyzacji i pracy z narzędziami programistycznymi.', example: 'vercel --prod publikuje projekt na Vercel z poziomu terminala.', tags: ['narzędzia', 'terminal'], related: ['IDE', 'Build', 'Deploy'] },
  { id: 'ide', title: 'IDE', category: 'Kod i narzędzia', definition: 'Integrated Development Environment — środowisko łączące edytor kodu, podpowiedzi, debugowanie i narzędzia projektu.', context: 'IDE rozumie strukturę projektu i pomaga szybciej poruszać się po kodzie.', example: 'Visual Studio Code z rozszerzeniami może pełnić rolę lekkiego IDE.', tags: ['kod', 'narzędzia'], related: ['VS Code', 'Debugowanie', 'Compiler'] },
  { id: 'vscode', title: 'VS Code', category: 'Kod i narzędzia', definition: 'Visual Studio Code — popularny, rozszerzalny edytor kodu firmy Microsoft.', context: 'VS Code obsługuje wiele języków, Git, terminal i dodatki do pracy z frameworkami.', example: 'Otwórz folder projektu w VS Code, aby edytować HTML, CSS i JavaScript w jednym miejscu.', tags: ['edytor', 'kod'], related: ['IDE', 'CLI', 'Git'] },
  { id: 'branch', title: 'Branch', category: 'Kod i narzędzia', definition: 'Gałąź w Git — osobna linia zmian, na której można pracować bez naruszania głównej wersji projektu.', context: 'Branch ułatwia tworzenie funkcji, eksperymentów i poprawek przed ich połączeniem z main.', example: 'git switch -c nowa-wyszukiwarka', tags: ['Git', 'wersje'], related: ['Git', 'Merge', 'Pull request'] },
  { id: 'merge', title: 'Merge', category: 'Kod i narzędzia', definition: 'Scalenie zmian z jednej gałęzi Git z drugą, na przykład z główną gałęzią projektu.', context: 'Podczas merge Git może wykryć konflikt, gdy dwie gałęzie zmieniły ten sam fragment pliku.', example: 'Łączysz branch z poprawką błędu z gałęzią main po zakończeniu pracy.', tags: ['Git', 'wersje'], related: ['Branch', 'Pull request', 'Conflict'] },
  { id: 'pull-request', title: 'Pull request', category: 'Kod i narzędzia', definition: 'Prośba o dołączenie zmian z jednej gałęzi do innej, zwykle po przeglądzie kodu.', context: 'Pull request tworzy miejsce na komentarze, testy automatyczne i decyzję o połączeniu zmian.', example: 'Otwierasz PR „Dodaj 100 haseł do leksykonu” przed mergem do main.', tags: ['Git', 'współpraca'], related: ['Branch', 'Merge', 'CI/CD'] },
  { id: 'ci-cd', title: 'CI/CD', category: 'Kod i narzędzia', definition: 'Continuous Integration / Continuous Delivery — automatyczne testowanie, budowanie i dostarczanie zmian.', context: 'CI/CD skraca drogę od commita do działającej wersji i szybko pokazuje, gdy coś się zepsuło.', example: 'Po każdym pushu pipeline uruchamia testy i może wdrożyć aplikację na Vercel.', tags: ['automatyzacja', 'deploy'], related: ['Build', 'Test', 'Deploy'] },
  { id: 'test', title: 'Test', category: 'Kod i narzędzia', definition: 'Sprawdzenie, czy kod lub aplikacja zachowują się zgodnie z oczekiwaniami dla określonych danych wejściowych.', context: 'Test może sprawdzać pojedynczą funkcję, połączenie kilku modułów albo cały przepływ użytkownika.', example: 'Test wyszukiwarki sprawdza, czy wpisanie „CSS” pokazuje hasło CSS.', tags: ['jakość', 'kod'], related: ['Unit test', 'Debugowanie', 'CI/CD'] },
  { id: 'unit-test', title: 'Unit test', category: 'Kod i narzędzia', definition: 'Test jednostkowy — test małego, izolowanego fragmentu kodu, np. jednej funkcji.', context: 'Unit test jest szybki i precyzyjnie wskazuje, która reguła przestała działać.', example: 'Test sprawdza, czy funkcja pluralize(2) zwraca „2 hasła”.', tags: ['jakość', 'kod'], related: ['Test', 'CI/CD', 'Refactor'] },
  { id: 'debugging', title: 'Debugowanie', category: 'Kod i narzędzia', definition: 'Szukanie przyczyny błędnego działania programu i sprawdzanie hipotez prowadzących do poprawki.', context: 'Debugowanie zaczyna się od odtworzenia problemu, zebrania objawów i zawężenia miejsca, w którym coś poszło nie tak.', example: 'W DevTools sprawdzasz, dlaczego kliknięcie karty nie otwiera szczegółów hasła.', tags: ['kod', 'jakość'], related: ['DevTools', 'Test', 'Refactor'] },
  { id: 'refactor', title: 'Refactor', category: 'Kod i narzędzia', definition: 'Refaktoryzacja — zmiana wewnętrznej struktury kodu bez zmieniania jego widocznego działania.', context: 'Refaktor poprawia czytelność, usuwa duplikację i ułatwia dalszy rozwój bez dokładania funkcji.', example: 'Wydzielasz renderowanie karty hasła do osobnej funkcji, nie zmieniając wyglądu aplikacji.', tags: ['kod', 'utrzymanie'], related: ['Test', 'Component', 'Dependency'] },
  { id: 'environment-variable', title: 'Environment variable', category: 'Kod i narzędzia', definition: 'Zmienna środowiskowa — wartość dostarczana aplikacji z konfiguracji środowiska zamiast wpisywana bezpośrednio w kod.', context: 'Używa się jej do adresów usług, trybów pracy i sekretów, których nie powinno być w repozytorium.', example: 'DATABASE_URL jest wczytywany z ustawień środowiska podczas wdrożenia.', tags: ['konfiguracja', 'bezpieczeństwo'], related: ['Deploy', 'Backend', 'Secret'] },
  { id: 'dependency', title: 'Dependency', category: 'Kod i narzędzia', definition: 'Zależność — zewnętrzny pakiet, biblioteka albo narzędzie wymagane przez projekt do działania lub budowania.', context: 'Każda zależność zwiększa możliwości projektu, ale też wymaga aktualizacji i oceny bezpieczeństwa.', example: 'React jest zależnością aplikacji, która używa go do renderowania interfejsu.', tags: ['kod', 'narzędzia'], related: ['Library', 'npm', 'Package manager'] },
  { id: 'runtime', title: 'Runtime', category: 'Kod i narzędzia', definition: 'Środowisko uruchomieniowe, które wykonuje kod programu i udostępnia mu potrzebne API.', context: 'Ten sam kod może zachowywać się inaczej w przeglądarce, Node.js albo środowisku edge.', example: 'Node.js uruchamia JavaScript poza przeglądarką, na przykład po stronie serwera.', tags: ['kod', 'środowisko'], related: ['JavaScript', 'Backend', 'Framework'] },
  { id: 'compiler', title: 'Compiler', category: 'Kod i narzędzia', definition: 'Kompilator — program tłumaczący kod źródłowy na inną postać, często łatwiejszą do uruchomienia przez komputer.', context: 'Kompilator może też wykrywać błędy typów i optymalizować wynikowy kod.', example: 'TypeScript jest kompilowany do JavaScriptu zrozumiałego dla przeglądarki.', tags: ['kod', 'narzędzia'], related: ['TypeScript', 'Build', 'Runtime'] },
  { id: 'interpreter', title: 'Interpreter', category: 'Kod i narzędzia', definition: 'Interpreter — program wykonujący kod, zwykle instrukcja po instrukcji, bez wcześniejszego tworzenia osobnego pliku wynikowego.', context: 'Interpreter ułatwia szybkie eksperymenty, ale sposób wykonania zależy od konkretnego języka i środowiska.', example: 'Interpreter Pythona wykonuje polecenie print("Witaj") od razu po jego wpisaniu.', tags: ['kod', 'runtime'], related: ['Python', 'Runtime', 'Compiler'] },
  { id: 'database', title: 'Baza danych', category: 'Kod i narzędzia', definition: 'System do trwałego przechowywania, organizowania i odczytywania danych aplikacji.', context: 'Baza danych pilnuje struktury, wyszukiwania i spójności informacji lepiej niż zwykły plik tekstowy.', example: 'Aplikacja przechowuje w bazie tytuł hasła, definicję, kategorię i datę aktualizacji.', tags: ['dane', 'backend'], related: ['SQL', 'NoSQL', 'CRUD'] },
  { id: 'sql', title: 'SQL', category: 'Kod i narzędzia', definition: 'Structured Query Language — język zapytań używany do pracy z relacyjnymi bazami danych.', context: 'SQL pozwala wyszukiwać, łączyć, dodawać i aktualizować dane w tabelach.', example: 'SELECT title FROM terms WHERE category = "AI i dane";', tags: ['dane', 'backend'], related: ['Baza danych', 'CRUD', 'API'] },
  { id: 'nosql', title: 'NoSQL', category: 'Kod i narzędzia', definition: 'Grupa baz danych, które nie muszą używać klasycznego modelu tabel i relacji SQL.', context: 'NoSQL bywa wygodny przy elastycznej strukturze dokumentów, dużej skali albo szybkiej zmianie modelu danych.', example: 'Jedno hasło może być zapisane jako dokument JSON z listą tagów i powiązań.', tags: ['dane', 'backend'], related: ['Baza danych', 'JSON', 'CRUD'] },
  { id: 'crud', title: 'CRUD', category: 'Kod i narzędzia', definition: 'Skrót od Create, Read, Update, Delete — czterech podstawowych operacji na danych.', context: 'Większość aplikacji przechowujących informacje potrzebuje przynajmniej części tego cyklu.', example: 'Dodaj hasło = Create, otwórz = Read, popraw = Update, usuń = Delete.', tags: ['dane', 'backend'], related: ['Baza danych', 'API', 'SQL'] },
  { id: 'authentication', title: 'Authentication', category: 'Kod i narzędzia', definition: 'Uwierzytelnianie — sprawdzanie, kim jest osoba lub system próbujący uzyskać dostęp.', context: 'Logowanie odpowiada na pytanie „kto to jest?”, a autoryzacja na pytanie „co może zrobić?”.', example: 'Użytkownik podaje e-mail i hasło, a system tworzy dla niego sesję.', tags: ['bezpieczeństwo', 'konto'], related: ['Authorization', 'Session', 'OAuth'] },
  { id: 'oauth', title: 'OAuth', category: 'Kod i narzędzia', definition: 'Standard pozwalający aplikacji uzyskać ograniczony dostęp bez poznawania hasła do zewnętrznego konta.', context: 'OAuth umożliwia przyciski typu „Zaloguj przez Google” lub dostęp do wybranych danych usługi.', example: 'Aplikacja przekierowuje Cię do Google, a potem otrzymuje zgodę i token dostępu.', tags: ['bezpieczeństwo', 'konto'], related: ['Authentication', 'API', 'Token'] },
  { id: 'endpoint', title: 'Endpoint', category: 'Kod i narzędzia', definition: 'Konkretny adres API obsługujący określony rodzaj danych lub operacji.', context: 'Endpoint łączy metodę HTTP, adres, parametry wejściowe i format odpowiedzi.', example: 'GET /api/terms zwraca listę haseł, a POST /api/terms tworzy nowe.', tags: ['API', 'backend'], related: ['API', 'HTTP', 'JSON'] },
  { id: 'cpu', title: 'CPU', category: 'Komputer', definition: 'Central Processing Unit — procesor wykonujący instrukcje programów i koordynujący pracę komputera.', context: 'CPU wpływa na szybkość wielu operacji, ale nie jest jedynym elementem decydującym o wydajności.', example: 'Podczas kompilowania projektu CPU wykonuje wiele obliczeń potrzebnych do przygotowania plików.', tags: ['sprzęt', 'wydajność'], related: ['GPU', 'RAM', 'Motherboard'] },
  { id: 'gpu', title: 'GPU', category: 'Komputer', definition: 'Graphics Processing Unit — procesor wyspecjalizowany w równoległych obliczeniach, grafice i niektórych zadaniach AI.', context: 'GPU potrafi jednocześnie wykonywać bardzo wiele podobnych operacji, dlatego jest ważny przy obrazie i trenowaniu modeli.', example: 'Renderowanie grafiki 3D i obliczenia sieci neuronowej mogą korzystać z GPU.', tags: ['sprzęt', 'AI'], related: ['CPU', 'Neural network', 'RAM'] },
  { id: 'motherboard', title: 'Motherboard', category: 'Komputer', definition: 'Płyta główna — główna płytka komputera łącząca procesor, pamięć, dyski i urządzenia dodatkowe.', context: 'Płyta główna określa między innymi, jakie podzespoły i standardy można zastosować w komputerze.', example: 'RAM, CPU i karta graficzna komunikują się przez połączenia na płycie głównej.', tags: ['sprzęt', 'komputer'], related: ['CPU', 'GPU', 'Driver'] },
  { id: 'operating-system', title: 'Operating system', category: 'Komputer', definition: 'System operacyjny — podstawowe oprogramowanie zarządzające sprzętem i umożliwiające uruchamianie aplikacji.', context: 'System operacyjny udostępnia programom pliki, pamięć, urządzenia i zasady bezpieczeństwa.', example: 'Windows, macOS i Linux uruchamiają przeglądarkę oraz zarządzają plikami projektu.', tags: ['system', 'komputer'], related: ['Linux', 'Windows', 'Runtime'] },
  { id: 'linux', title: 'Linux', category: 'Komputer', definition: 'Rodzina systemów operacyjnych opartych na jądrze Linux, popularna na serwerach i w pracy programistycznej.', context: 'Linux występuje w wielu dystrybucjach, które różnią się zestawem narzędzi i sposobem konfiguracji.', example: 'Serwer może działać na Ubuntu, a programista używać terminala Linux do uruchamiania projektu.', tags: ['system', 'serwer'], related: ['Operating system', 'CLI', 'Backend'] },
  { id: 'windows', title: 'Windows', category: 'Komputer', definition: 'System operacyjny firmy Microsoft używany na komputerach osobistych i w środowiskach firmowych.', context: 'Windows zapewnia graficzny interfejs, obsługę urządzeń, plików i aplikacji.', example: 'Na Windows możesz otworzyć Ayonis Leksykon w przeglądarce i edytować pliki w VS Code.', tags: ['system', 'komputer'], related: ['Operating system', 'Driver', 'Browser'] },
  { id: 'firmware', title: 'Firmware', category: 'Komputer', definition: 'Oprogramowanie zapisane w urządzeniu, które steruje jego podstawowym działaniem na niskim poziomie.', context: 'Firmware działa przed systemem operacyjnym lub niezależnie od niego, np. w routerze, dysku czy płycie głównej.', example: 'Aktualizacja firmware routera może poprawić jego stabilność i bezpieczeństwo.', tags: ['sprzęt', 'system'], related: ['Driver', 'Operating system', 'Security'] },
  { id: 'driver', title: 'Driver', category: 'Komputer', definition: 'Sterownik — oprogramowanie pozwalające systemowi operacyjnemu komunikować się z konkretnym urządzeniem.', context: 'Bez właściwego sterownika system może nie rozpoznać drukarki, karty graficznej albo urządzenia audio.', example: 'Instalujesz sterownik GPU, aby program mógł korzystać z karty graficznej.', tags: ['sprzęt', 'system'], related: ['Firmware', 'GPU', 'Operating system'] },
  { id: 'ip-address', title: 'IP address', category: 'Komputer', definition: 'Adres IP — numer identyfikujący urządzenie lub interfejs sieciowy w danej sieci.', context: 'Adres IP może być lokalny, widoczny tylko w domu lub biurze, albo publiczny w internecie.', example: 'Komputer łączy się z routerem pod adresem 192.168.1.10.', tags: ['sieć', 'komputer'], related: ['DNS', 'Wi-Fi', 'Firewall'] },
  { id: 'wifi', title: 'Wi-Fi', category: 'Komputer', definition: 'Technologia bezprzewodowego łączenia urządzeń z siecią lokalną i internetem.', context: 'Jakość Wi-Fi zależy między innymi od odległości, przeszkód, zakłóceń i obciążenia sieci.', example: 'Laptop korzysta z Wi-Fi, aby pobrać pliki strony z hostingu.', tags: ['sieć', 'komputer'], related: ['IP address', 'DNS', 'Firewall'] },
  { id: 'backup', title: 'Backup', category: 'Komputer', definition: 'Kopia zapasowa — dodatkowa kopia danych przechowywana na wypadek utraty, uszkodzenia albo pomyłki.', context: 'Dobry backup jest regularny, oddzielony od głównych danych i okresowo sprawdzany przez próbę odtworzenia.', example: 'Kopiujesz folder projektu i ważne dokumenty na drugi dysk lub do bezpiecznej chmury.', tags: ['dane', 'bezpieczeństwo'], related: ['Encryption', 'Cloud computing', 'Database'] },
  { id: 'encryption', title: 'Encryption', category: 'Komputer', definition: 'Szyfrowanie — zamiana danych w postać możliwą do odczytania tylko dla osoby lub systemu z odpowiednim kluczem.', context: 'Szyfrowanie chroni dane podczas przesyłania i przechowywania, ale nie zastępuje dobrych haseł ani kopii zapasowych.', example: 'HTTPS szyfruje dane wysyłane z formularza do serwera.', tags: ['bezpieczeństwo', 'dane'], related: ['HTTPS', 'SSL/TLS', 'Backup'] },
  { id: 'firewall', title: 'Firewall', category: 'Komputer', definition: 'Zapora sieciowa — mechanizm kontrolujący dozwolony ruch między urządzeniem, siecią i internetem.', context: 'Firewall może blokować niechciane połączenia według adresu, portu, aplikacji albo reguły bezpieczeństwa.', example: 'Zapora blokuje połączenia przychodzące do usługi, która nie powinna być publicznie dostępna.', tags: ['sieć', 'bezpieczeństwo'], related: ['IP address', 'HTTPS', 'Cloud computing'] },
  { id: 'cloud-computing', title: 'Cloud computing', category: 'Komputer', definition: 'Chmura obliczeniowa — korzystanie z mocy obliczeniowej, przechowywania i usług przez internet zamiast wyłącznie lokalnie.', context: 'Chmura pozwala skalować zasoby i uruchamiać projekt bez kupowania własnego serwera.', example: 'Vercel udostępnia aplikację z serwerów dostępnych przez internet.', tags: ['chmura', 'web'], related: ['Hosting', 'Backend', 'Backup'] },
  { id: 'copywriting', title: 'Copywriting', category: 'Tekst i treść', definition: 'Pisanie tekstów, które przekazują informację i pomagają odbiorcy wykonać określone działanie.', context: 'Dobry copywriting łączy jasność, korzyść dla odbiorcy i właściwy ton, zamiast używać samych haseł reklamowych.', example: 'Zamiast „Innowacyjna platforma” napisz „Znajdź definicję techniczną w kilka sekund”.', tags: ['tekst', 'komunikacja'], related: ['UX writing', 'Content', 'CTA'] },
  { id: 'content', title: 'Content', category: 'Tekst i treść', definition: 'Treść — informacje publikowane w produkcie lub kanale, np. tekst, obraz, nagranie, dokumentacja albo wpis.', context: 'Content powinien mieć odbiorcę, cel i formę dopasowaną do miejsca, w którym będzie czytany.', example: 'Definicja, przykład i kontekst hasła są contentem Ayonis Leksykon.', tags: ['tekst', 'web'], related: ['Copywriting', 'CMS', 'SEO'] },
  { id: 'wysiwyg', title: 'WYSIWYG', category: 'Tekst i treść', definition: 'What You See Is What You Get — edytor pokazujący treść w sposób zbliżony do jej finalnego wyglądu.', context: 'WYSIWYG pozwala formatować tekst bez znajomości HTML-u, ale czasem ukrywa strukturę generowanego dokumentu.', example: 'Pogrubiasz słowo w edytorze, widząc od razu efekt zamiast wpisywać znacznik ręcznie.', tags: ['tekst', 'edytor'], related: ['Markdown', 'HTML', 'CMS'] },
  { id: 'ux-writing', title: 'UX writing', category: 'Tekst i treść', definition: 'Pisanie krótkich tekstów w interfejsie tak, aby prowadziły użytkownika i wyjaśniały działanie produktu.', context: 'To etykiety przycisków, komunikaty błędów, podpowiedzi, puste stany i teksty formularzy.', example: '„Wyczyść wyszukiwanie” mówi dokładnie, co zrobi przycisk, lepiej niż samo „OK”.', tags: ['tekst', 'design'], related: ['Copywriting', 'UI', 'Accessibility'] },
  { id: 'plain-language', title: 'Plain language', category: 'Tekst i treść', definition: 'Prosty język — sposób pisania, w którym odbiorca może szybko znaleźć, zrozumieć i użyć informacji.', context: 'Prosty język nie oznacza spłycania. Oznacza krótsze zdania, konkretne czasowniki i wyjaśnianie skrótów.', example: 'Zamiast „dokonaj implementacji” napisz „zbuduj tę funkcję”.', tags: ['tekst', 'komunikacja'], related: ['UX writing', 'Accessibility', 'Copywriting'] },
  { id: 'proofreading', title: 'Proofreading', category: 'Tekst i treść', definition: 'Korekta — końcowe sprawdzenie tekstu pod kątem języka, literówek, spójności i błędów formatowania.', context: 'Korekta jest osobnym etapem od pisania i redakcji, dlatego łatwiej zauważyć błędy po przerwie.', example: 'Przed publikacją leksykonu sprawdzasz polskie znaki, interpunkcję i jednolity zapis skrótów.', tags: ['tekst', 'jakość'], related: ['Content', 'Plain language', 'Versioning'] },
  { id: 'content-model', title: 'Content model', category: 'Tekst i treść', definition: 'Model treści — opis typów informacji, ich pól, relacji i zasad przechowywania w projekcie.', context: 'Model treści pomaga przejść od pojedynczego tekstu do uporządkowanej bazy, którą można filtrować i rozwijać.', example: 'Hasło ma tytuł, kategorię, definicję, kontekst, przykład, tagi i powiązania.', tags: ['dane', 'treść'], related: ['CMS', 'Database', 'JSON'] },
  { id: 'glossary', title: 'Glossary', category: 'Tekst i treść', definition: 'Glosariusz — uporządkowana lista terminów z definicjami, często ograniczona do konkretnej dziedziny lub projektu.', context: 'Glosariusz ustala wspólne znaczenie słów, dzięki czemu zespół nie używa tych samych terminów w różny sposób.', example: 'Ayonis Leksykon jest glosariuszem technologii, AI, webu i narzędzi.', tags: ['tekst', 'wiedza'], related: ['Content model', 'SEO', 'CMS'] },
  { id: 'design-system', title: 'Design system', category: 'Projektowanie', definition: 'System projektowy — zestaw zasad, komponentów, stylów i wzorców służących do budowania spójnych interfejsów.', context: 'Design system łączy decyzje projektowe z gotowymi elementami kodu, dzięki czemu produkt rośnie bez chaosu.', example: 'Kolory, typografia, przyciski i karty Ayonis Leksykon mogą tworzyć jeden system projektowy.', tags: ['design', 'interfejs'], related: ['Component', 'Design token', 'UI'] },
  { id: 'wireframe', title: 'Wireframe', category: 'Projektowanie', definition: 'Makieta szkieletowa pokazująca układ treści i funkcji bez dopracowanych kolorów i ozdobników.', context: 'Wireframe pomaga sprawdzić hierarchię i przepływ zanim zespół poświęci czas na finalny wygląd.', example: 'Prosty szkic ekranu pokazuje miejsce wyszukiwarki, kategorii i listy haseł.', tags: ['design', 'planowanie'], related: ['Prototype', 'User flow', 'UI'] },
  { id: 'prototype', title: 'Prototype', category: 'Projektowanie', definition: 'Prototyp — testowa, często interaktywna wersja produktu lub ekranu, służąca do sprawdzenia pomysłu.', context: 'Prototyp może być klikalną makietą albo działającym fragmentem kodu, ale nie musi być gotowym produktem.', example: 'Przed programowaniem sprawdzasz, czy kliknięcie kategorii prowadzi do właściwej listy.', tags: ['design', 'testy'], related: ['Wireframe', 'User flow', 'UX'] },
  { id: 'user-flow', title: 'User flow', category: 'Projektowanie', definition: 'Ścieżka użytkownika — kolejne kroki prowadzące od celu do wykonania zadania w produkcie.', context: 'Rozpisanie user flow ujawnia zbędne ekrany, niejasne decyzje i miejsca, w których użytkownik może się zgubić.', example: 'Otwórz aplikację → wpisz hasło → wybierz wynik → przeczytaj przykład → wróć do kategorii.', tags: ['UX', 'planowanie'], related: ['UX', 'Wireframe', 'Information architecture'] },
  { id: 'persona', title: 'Persona', category: 'Projektowanie', definition: 'Opis reprezentatywnego typu użytkownika, jego celu, potrzeb, ograniczeń i sposobu pracy.', context: 'Persona pomaga podejmować decyzje projektowe z myślą o konkretnej osobie, a nie o abstrakcyjnym „każdym”.', example: 'Persona Ayonis Leksykon: osoba ucząca się technologii, która chce szybko znaleźć proste wyjaśnienie.', tags: ['UX', 'badania'], related: ['UX', 'User flow', 'Usability'] },
  { id: 'cta', title: 'CTA', category: 'Projektowanie', definition: 'Call to Action — element zachęcający użytkownika do konkretnego działania.', context: 'Dobre CTA mówi, co się wydarzy po kliknięciu i odpowiada etapowi, na którym jest użytkownik.', example: '„Dodaj własne hasło” jest CTA, bo jasno wskazuje następny krok.', tags: ['design', 'tekst'], related: ['UX writing', 'UI', 'Copywriting'] },
  { id: 'typography', title: 'Typography', category: 'Projektowanie', definition: 'Typografia — dobór i układ krojów pisma, rozmiarów, odstępów, grubości i długości wierszy.', context: 'Typografia wpływa na hierarchię, tempo czytania i charakter produktu równie mocno jak kolor.', example: 'Duży serifowy tytuł odróżnia nazwę hasła od spokojniejszej definicji sans-serif.', tags: ['design', 'tekst'], related: ['UI', 'Spacing', 'Accessibility'] },
  { id: 'contrast', title: 'Contrast', category: 'Projektowanie', definition: 'Kontrast — różnica między kolorami, rozmiarami, grubościami lub kształtami elementów.', context: 'Kontrast buduje hierarchię, ale dla tekstu jest także ważnym warunkiem czytelności i dostępności.', example: 'Nagłówek powinien wyraźnie odróżniać się od tła, a główny przycisk od przycisku drugorzędnego.', tags: ['design', 'dostępność'], related: ['Accessibility', 'Typography', 'UI'] },
  { id: 'spacing', title: 'Spacing', category: 'Projektowanie', definition: 'Spacing — system odstępów między elementami interfejsu, który porządkuje układ i rytm strony.', context: 'Spójne odstępy pomagają rozpoznać, które elementy należą do jednej grupy, a które są od siebie niezależne.', example: 'Karta ma większy odstęp od kolejnej karty niż tytuł od definicji w tej samej karcie.', tags: ['design', 'układ'], related: ['Typography', 'Design system', 'UI'] },
  { id: 'usability', title: 'Usability', category: 'Projektowanie', definition: 'Użyteczność — miara tego, jak łatwo, skutecznie i bezbłędnie użytkownik wykonuje zadanie.', context: 'Użyteczność można badać obserwacją, testami z osobami i analizą miejsc, w których użytkownicy rezygnują.', example: 'Jeśli ktoś znajduje „CSS” po wpisaniu css bez dodatkowej instrukcji, wyszukiwarka ma dobrą użyteczność.', tags: ['UX', 'testy'], related: ['UX', 'Accessibility', 'User flow'] },
  { id: 'information-architecture', title: 'Information architecture', category: 'Projektowanie', definition: 'Architektura informacji — sposób organizowania treści, kategorii, nazw i nawigacji w produkcie.', context: 'Dobra architektura odpowiada na pytanie, gdzie użytkownik spodziewa się znaleźć daną informację.', example: 'Podział na AI, Web, Kod, Komputer, Tekst i Projektowanie pomaga odnaleźć właściwy obszar.', tags: ['UX', 'treść'], related: ['User flow', 'Glossary', 'Design system'] },
  { id: 'design-token', title: 'Design token', category: 'Projektowanie', definition: 'Token projektowy — nazwany zapis decyzji wizualnej, np. koloru, odstępu, promienia narożnika albo cienia.', context: 'Tokeny ułatwiają zmianę całego stylu produktu bez ręcznego poprawiania każdego komponentu.', example: '--accent: #c86d4f jest tokenem koloru używanym w wielu miejscach interfejsu.', tags: ['design', 'kod'], related: ['Design system', 'CSS', 'Component'] },
];

const state = { terms: [], query: '', view: 'all', activeCategory: null, layout: 'grid', selectedId: null, dark: localStorage.getItem('slowo-dark') === 'true' };
const els = {};

function loadTerms() {
  const custom = JSON.parse(localStorage.getItem('slowo-custom-terms') || '[]');
  const removed = JSON.parse(localStorage.getItem('slowo-removed-terms') || '[]');
  const allSeedTerms = [...seedTerms, ...extraTerms];
  state.terms = [...allSeedTerms.filter(term => !removed.includes(term.id)), ...custom];
}

function getFavorites() { return JSON.parse(localStorage.getItem('slowo-favorites') || '[]'); }
function getRecent() { return JSON.parse(localStorage.getItem('slowo-recent') || '[]'); }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function isFavorite(id) { return getFavorites().includes(id); }
function categoryStyle(category) { return `--category-color: ${categories[category]?.color || '#668270'}`; }
function pluralize(count) { return `${count} ${count === 1 ? 'hasło' : count > 1 && count < 5 ? 'hasła' : 'haseł'}`; }

function filteredTerms() {
  let list = [...state.terms];
  if (state.view === 'favorites') list = list.filter(term => isFavorite(term.id));
  if (state.view === 'recent') { const recent = getRecent(); list = recent.map(id => state.terms.find(term => term.id === id)).filter(Boolean); }
  if (state.activeCategory) list = list.filter(term => term.category === state.activeCategory);
  const query = state.query.trim().toLocaleLowerCase('pl-PL');
  if (query) list = list.filter(term => [term.title, term.category, term.definition, term.context, term.example, ...(term.tags || [])].join(' ').toLocaleLowerCase('pl-PL').includes(query));
  return list;
}

function renderCategories() {
  const counts = Object.fromEntries(Object.keys(categories).map(category => [category, state.terms.filter(term => term.category === category).length]));
  els.categoryList.innerHTML = Object.entries(categories).map(([name, info]) => `<button class="category-item ${state.activeCategory === name ? 'active' : ''}" data-category="${name}" type="button" style="${categoryStyle(name)}"><span></span><strong>${name}</strong><b>${counts[name] || 0}</b></button>`).join('');
  els.categorySelect.innerHTML = Object.keys(categories).map(name => `<option>${name}</option>`).join('');
}

function renderNav() {
  document.querySelectorAll('.nav-item').forEach(button => button.classList.toggle('active', button.dataset.view === state.view && !state.activeCategory));
  els.allCount.textContent = state.terms.length;
  els.favoriteCount.textContent = getFavorites().filter(id => state.terms.some(term => term.id === id)).length;
  els.recentCount.textContent = getRecent().filter(id => state.terms.some(term => term.id === id)).length;
}

function termCardMarkup(term) {
  return `<article class="term-card" style="${categoryStyle(term.category)}" data-id="${term.id}">
    <div class="term-top"><span class="category-pill"><i></i>${term.category}</span><button class="favorite-button ${isFavorite(term.id) ? 'active' : ''}" data-favorite="${term.id}" type="button" aria-label="${isFavorite(term.id) ? 'Usuń z ulubionych' : 'Dodaj do ulubionych'}">${isFavorite(term.id) ? '★' : '☆'}</button></div>
    <h3>${term.title}</h3><p class="term-definition">${term.definition}</p>
    <div class="term-bottom"><div class="term-tags">${(term.tags || []).slice(0, 2).map(tag => `<span class="term-tag">${tag}</span>`).join('')}</div><button class="open-term" data-open="${term.id}" type="button">Otwórz →</button></div>
  </article>`;
}

function renderCards() {
  const terms = filteredTerms();
  els.termGrid.classList.toggle('list-layout', state.layout === 'list');
  const grouped = state.view === 'all' && !state.activeCategory && !state.query;
  if (grouped) {
    els.termGrid.innerHTML = Object.keys(categories).filter(category => terms.some(term => term.category === category)).map(category => {
      const groupTerms = terms.filter(term => term.category === category);
      const info = categories[category];
      return `<section class="category-group" style="${categoryStyle(category)}">
        <header class="category-group-header"><div><span class="category-group-symbol" aria-hidden="true">${info.icon}</span><h3>${category}</h3><span class="category-group-count">${pluralize(groupTerms.length)}</span></div><button data-group-category="${category}" type="button">Pokaż tylko →</button></header>
        <div class="category-group-grid">${groupTerms.map(termCardMarkup).join('')}</div>
      </section>`;
    }).join('');
  } else {
    els.termGrid.innerHTML = terms.map(termCardMarkup).join('');
  }
  els.emptyState.hidden = terms.length > 0;
  els.termGrid.hidden = terms.length === 0;
  const title = state.query ? `Wyniki dla „${state.query}”` : state.activeCategory || ({ all: 'Wszystkie hasła', favorites: 'Ulubione', recent: 'Ostatnio oglądane' }[state.view]);
  els.resultsTitle.textContent = title;
  els.resultCount.textContent = pluralize(terms.length);
  els.resultsSubtitle.textContent = state.query ? 'Hasła dopasowane do nazwy, definicji, kategorii i tagów.' : 'Wybierz hasło, żeby zobaczyć definicję i przykład.';
  els.breadcrumbCurrent.textContent = title;
}

function render() { renderCategories(); renderNav(); renderCards(); }

function toggleFavorite(id) {
  const favorites = getFavorites();
  const next = favorites.includes(id) ? favorites.filter(item => item !== id) : [...favorites, id];
  save('slowo-favorites', next); render();
  if (state.selectedId === id) renderDetail(state.terms.find(term => term.id === id));
}

function openDetail(id) {
  const term = state.terms.find(item => item.id === id); if (!term) return;
  state.selectedId = id;
  const recent = getRecent().filter(item => item !== id); save('slowo-recent', [id, ...recent].slice(0, 8)); renderNav();
  renderDetail(term); els.overlay.hidden = false; els.detailDrawer.classList.add('open'); els.detailDrawer.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden';
}

function exampleFor(term) {
  if (term.example && term.example.trim()) return term.example.trim();
  const fallbackByCategory = {
    'AI i dane': `Przykład: zapisz, jak hasło „${term.title}” wykorzystujesz w swoim narzędziu AI.`,
    'Web i strony': `Przykład: wskaż miejsce, w którym „${term.title}” pojawia się na Twojej stronie.`,
    'Kod i narzędzia': `Przykład: dodaj krótką komendę lub sytuację, w której używasz „${term.title}”.`,
    'Tekst i treść': `Przykład: pokaż jedno zdanie albo fragment tekstu z użyciem „${term.title}”.`,
    'Komputer': `Przykład: opisz sytuację, w której „${term.title}” wpływa na pracę komputera.`,
    'Projektowanie': `Przykład: pokaż element interfejsu, w którym widać zasadę „${term.title}”.`,
  };
  return fallbackByCategory[term.category] || `Przykład użycia hasła „${term.title}”.`;
}

function renderDetail(term) {
  if (!term) return;
  els.detailContent.innerHTML = `<div class="detail-header" style="${categoryStyle(term.category)}"><span class="category-pill"><i></i>${term.category}</span><h2>${term.title}</h2><p>${term.definition}</p></div>
    <div class="detail-section"><h3>W praktyce</h3><p>${term.context || 'Dodaj własny kontekst, kiedy będziesz rozbudowywać to hasło.'}</p></div>
    <div class="detail-section"><h3>Przykład</h3><div class="code-block">${exampleFor(term)}</div></div>
    ${(term.related || []).length ? `<div class="detail-section"><h3>Powiązane hasła</h3><div class="related-list">${term.related.map(name => `<button class="related-term" data-related="${name}" type="button">${name} ↗</button>`).join('')}</div></div>` : ''}
    <div class="detail-actions"><button class="detail-favorite ${isFavorite(term.id) ? 'active' : ''}" data-detail-favorite="${term.id}" type="button">${isFavorite(term.id) ? '★ W ulubionych' : '☆ Dodaj do ulubionych'}</button></div>`;
}

function closeDetail() { els.detailDrawer.classList.remove('open'); els.detailDrawer.setAttribute('aria-hidden', 'true'); els.overlay.hidden = true; document.body.style.overflow = ''; }

function addCustomTerm(form) {
  const data = new FormData(form); const title = data.get('title').trim();
  const term = { id: `custom-${Date.now()}`, title, category: data.get('category'), definition: data.get('definition').trim(), context: 'To hasło zostało dodane do Twojej prywatnej Słowobazy.', example: data.get('example').trim(), tags: ['własne'], related: [] };
  const custom = JSON.parse(localStorage.getItem('slowo-custom-terms') || '[]'); save('slowo-custom-terms', [...custom, term]); state.terms.push(term); form.reset(); els.addDialog.close(); state.view = 'all'; state.activeCategory = null; openDetail(term.id); render();
}

function setup() {
  Object.assign(els, { categoryList: document.querySelector('#categoryList'), categorySelect: document.querySelector('#categorySelect'), allCount: document.querySelector('#allCount'), favoriteCount: document.querySelector('#favoriteCount'), recentCount: document.querySelector('#recentCount'), searchInput: document.querySelector('#searchInput'), clearSearch: document.querySelector('#clearSearch'), termGrid: document.querySelector('#termGrid'), emptyState: document.querySelector('#emptyState'), resultsTitle: document.querySelector('#resultsTitle'), resultsSubtitle: document.querySelector('#resultsSubtitle'), resultCount: document.querySelector('#resultCount'), breadcrumbCurrent: document.querySelector('#breadcrumbCurrent'), overlay: document.querySelector('#overlay'), detailDrawer: document.querySelector('#detailDrawer'), detailContent: document.querySelector('#detailContent'), addDialog: document.querySelector('#addDialog'), addForm: document.querySelector('#addForm') });
  loadTerms(); document.body.classList.toggle('dark-mode', state.dark); render();
  els.searchInput.addEventListener('input', event => { state.query = event.target.value; els.clearSearch.classList.toggle('visible', Boolean(state.query)); renderCards(); });
  els.searchInput.addEventListener('keydown', event => { if (event.key === 'Enter' && filteredTerms()[0]) openDetail(filteredTerms()[0].id); });
  els.clearSearch.addEventListener('click', () => { state.query = ''; els.searchInput.value = ''; els.clearSearch.classList.remove('visible'); renderCards(); els.searchInput.focus(); });
  els.categoryList.addEventListener('click', event => { const button = event.target.closest('[data-category]'); if (!button) return; state.activeCategory = state.activeCategory === button.dataset.category ? null : button.dataset.category; state.view = 'all'; render(); });
  document.querySelector('.main-nav').addEventListener('click', event => { const button = event.target.closest('[data-view]'); if (!button) return; state.view = button.dataset.view; state.activeCategory = null; render(); });
  els.termGrid.addEventListener('click', event => { const group = event.target.closest('[data-group-category]'); if (group) { state.activeCategory = group.dataset.groupCategory; state.view = 'all'; render(); return; } const favorite = event.target.closest('[data-favorite]'); if (favorite) return toggleFavorite(favorite.dataset.favorite); const open = event.target.closest('[data-open]'); if (open) openDetail(open.dataset.open); });
  document.querySelector('.view-controls').addEventListener('click', event => { const button = event.target.closest('[data-layout]'); if (!button) return; state.layout = button.dataset.layout; document.querySelectorAll('.view-button').forEach(item => item.classList.toggle('active', item === button)); renderCards(); });
  document.querySelector('#focusSearchButton').addEventListener('click', () => els.searchInput.focus());
  document.querySelector('#themeButton').addEventListener('click', () => { state.dark = !state.dark; document.body.classList.toggle('dark-mode', state.dark); save('slowo-dark', state.dark); });
  document.querySelector('#closeDrawer').addEventListener('click', closeDetail); els.overlay.addEventListener('click', closeDetail);
  els.detailContent.addEventListener('click', event => { const fav = event.target.closest('[data-detail-favorite]'); if (fav) return toggleFavorite(fav.dataset.detailFavorite); const related = event.target.closest('[data-related]'); if (related) { const term = state.terms.find(item => item.title.toLocaleLowerCase('pl-PL') === related.dataset.related.toLocaleLowerCase('pl-PL')); if (term) openDetail(term.id); } });
  document.querySelectorAll('#openAddButton, #emptyAddButton').forEach(button => button.addEventListener('click', () => els.addDialog.showModal()));
  els.addForm.addEventListener('submit', event => { event.preventDefault(); addCustomTerm(els.addForm); });
  document.querySelector('#mobileMenu').addEventListener('click', () => document.querySelector('#sidebar').classList.toggle('open'));
  document.querySelector('#resetButton').addEventListener('click', () => { if (!confirm('Usunąć własne hasła i przywrócić przykładową zawartość?')) return; localStorage.removeItem('slowo-custom-terms'); localStorage.removeItem('slowo-removed-terms'); state.terms = [...seedTerms, ...extraTerms]; state.view = 'all'; state.activeCategory = null; render(); });
  document.addEventListener('keydown', event => { if (event.key === '/' && document.activeElement.tagName !== 'INPUT' && document.activeElement.tagName !== 'TEXTAREA') { event.preventDefault(); els.searchInput.focus(); } if (event.key === 'Escape') closeDetail(); });
}

setup();

